vich_uploader:
    db_driver: orm

    mappings:
        nanny_image:
            uri_prefix: /images/nannies
            upload_destination: '%kernel.project_dir%/public/images/nannies'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
